services:
  - type: web
    name: n8n
    env: docker
    region: singapore
    plan: standard
    branch: main
    numInstances: 1
    healthCheckPath: /
    dockerfilePath: ./Dockerfile

    envVars:
      # ✅ Auth protection
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: "n8njude"
      - key: N8N_BASIC_AUTH_PASSWORD
        value: "supersecurepass123"

      # ✅ Fix webhook using correct domain
      - key: WEBHOOK_URL
        value: "https://n8ntest-x0mn.onrender.com/"

      # ✅ PostgreSQL configuration (external)
      - key: DB_TYPE
        value: postgres
      - key: DB_POSTGRESDB_HOST
        value: dpg-d0nd4opr0fns738t89ng-a.singapore-postgres.render.com
      - key: DB_POSTGRESDB_PORT
        value: "5432"
      - key: DB_POSTGRESDB_DATABASE
        value: n8n_db_boeo
      - key: DB_POSTGRESDB_USER
        value: n8njude
      - key: DB_POSTGRESDB_PASSWORD
        value: WEW1H5B7hzfaL1BNhofQ6kwSmNa7dWEo

      # ✅ Optional: timezone for logs and workflow timestamps
      - key: GENERIC_TIMEZONE
        value: Asia/Manila

    disk:
      name: n8nDisk
      mountPath: /home/node/.n8n
      sizeGB: 10
