services:
  - type: web
    name: n8n
    env: docker
    region: singapore # <— Updated to Singapore (if supported by Render)
    plan: standard
    branch: main
    numInstances: 1
    healthCheckPath: /
    envVars:
      # n8n authentication
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: "n8njude"
      - key: N8N_BASIC_AUTH_PASSWORD
        value: "supersecurepass123" # Change to your own
      # n8n network/webhook config
      - key: N8N_HOST
        value: "n8ntest-x0mn.onrender.com"
      - key: WEBHOOK_URL
        value: "https://n8ntest-x0mn.onrender.com/"
      - key: N8N_PORT
        value: "5678"
      # PostgreSQL credentials from Render-managed DB
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_HOST
        fromDatabase:
          name: n8nDB
          property: host
      - key: DB_POSTGRESDB_DATABASE
        fromDatabase:
          name: n8nDB
          property: database
      - key: DB_POSTGRESDB_PORT
        fromDatabase:
          name: n8nDB
          property: port
      - key: DB_POSTGRESDB_USER
        fromDatabase:
          name: n8nDB
          property: user
      - key: DB_POSTGRESDB_PASSWORD
        fromDatabase:
          name: n8nDB
          property: password
    disk:
      name: n8nDisk
      mountPath: /home/node/.n8n
      sizeGB: 10

databases:
  - name: n8nDB
    plan: starter
